POST http://localhost:8080/footballer
Content-Type: application/json

{
    "footballerName": "Nick",
    "footballerLast": "Nickovich"
 }

###

DELETE http://localhost:8080/footballer?id=3

###

GET http://localhost:8080/footballer?id=5